// MPDECIMAL_FUNCTION(function, argc_in, argc_out)

MPDECIMAL_FUNCTION(abs,            1, 1)
MPDECIMAL_FUNCTION(add,            2, 1)
// MPDECIMAL_FUNCTION(and,            2, 1)
MPDECIMAL_FUNCTION(canonical,      1, 1)
MPDECIMAL_FUNCTION(ceil,           1, 1)
MPDECIMAL_FUNCTION(check_nan,      1, 1)
MPDECIMAL_FUNCTION(check_nans,     2, 1)
MPDECIMAL_FUNCTION(compare,        2, 1)
MPDECIMAL_FUNCTION(compare_signal, 2, 1)
MPDECIMAL_FUNCTION(copy,           1, 1)
MPDECIMAL_FUNCTION(copy_abs,       1, 1)
MPDECIMAL_FUNCTION(copy_negate,    1, 1)
MPDECIMAL_FUNCTION(copy_sign,      2, 1)
MPDECIMAL_FUNCTION(div,            2, 1)
MPDECIMAL_FUNCTION(divint,         2, 1)
MPDECIMAL_FUNCTION(divmod,         2, 2)
MPDECIMAL_FUNCTION(exp,            1, 1)
MPDECIMAL_FUNCTION(floor,          1, 1)
MPDECIMAL_FUNCTION(fma,            3, 1)
MPDECIMAL_FUNCTION(invert,         1, 1)
MPDECIMAL_FUNCTION(invroot,        1, 1)
MPDECIMAL_FUNCTION(ln,             1, 1)
MPDECIMAL_FUNCTION(log10,          1, 1)
MPDECIMAL_FUNCTION(logb,           1, 1)
MPDECIMAL_FUNCTION(max,            2, 1)
MPDECIMAL_FUNCTION(max_mag,        2, 1)
MPDECIMAL_FUNCTION(min,            2, 1)
MPDECIMAL_FUNCTION(min_mag,        2, 1)
MPDECIMAL_FUNCTION(minus,          1, 1)
MPDECIMAL_FUNCTION(mul,            2, 1)
MPDECIMAL_FUNCTION(next_minus,     1, 1)
MPDECIMAL_FUNCTION(next_plus,      1, 1)
MPDECIMAL_FUNCTION(next_toward,    2, 1)
// MPDECIMAL_FUNCTION(new,            0, 1)
// MPDECIMAL_FUNCTION(or,             2, 1)
MPDECIMAL_FUNCTION(plus,           1, 1)
MPDECIMAL_FUNCTION(pow,            2, 1)
MPDECIMAL_FUNCTION(powmod,         3, 1)
MPDECIMAL_FUNCTION(quantize,       2, 1)
MPDECIMAL_FUNCTION(reduce,         1, 1)
MPDECIMAL_FUNCTION(rem,            2, 1)
MPDECIMAL_FUNCTION(rem_near,       2, 1)
MPDECIMAL_FUNCTION(rotate,         2, 1)
MPDECIMAL_FUNCTION(round_to_int,   1, 1)
MPDECIMAL_FUNCTION(round_to_intx,  1, 1)
MPDECIMAL_FUNCTION(scaleb,         2, 1)
MPDECIMAL_FUNCTION(shift,          2, 1)
MPDECIMAL_FUNCTION(sqrt,           1, 1)
MPDECIMAL_FUNCTION(sub,            2, 1)
MPDECIMAL_FUNCTION(trunc,          1, 1)
MPDECIMAL_FUNCTION(xor,            2, 1)

