// Nif functions with an automatically-generated definition. 

// NIF_FUNCTION(function, argc_in, argc_out)
NIF_FUNCTION(abs,            1, 1)
NIF_FUNCTION(add,            2, 1)
// NIF_FUNCTION(and,            2, 1)
NIF_FUNCTION(canonical,      1, 1)
NIF_FUNCTION(ceil,           1, 1)
NIF_FUNCTION(check_nan,      1, 1)
NIF_FUNCTION(check_nans,     2, 1)
NIF_FUNCTION(compare,        2, 1)
NIF_FUNCTION(compare_signal, 2, 1)
NIF_FUNCTION(copy,           1, 1)
NIF_FUNCTION(copy_abs,       1, 1)
NIF_FUNCTION(copy_negate,    1, 1)
NIF_FUNCTION(copy_sign,      2, 1)
NIF_FUNCTION(div,            2, 1)
NIF_FUNCTION(divint,         2, 1)
NIF_FUNCTION(divmod,         2, 2)
NIF_FUNCTION(exp,            1, 1)
NIF_FUNCTION(floor,          1, 1)
NIF_FUNCTION(fma,            3, 1)
NIF_FUNCTION(invert,         1, 1)
NIF_FUNCTION(invroot,        1, 1)
NIF_FUNCTION(ln,             1, 1)
NIF_FUNCTION(log10,          1, 1)
NIF_FUNCTION(logb,           1, 1)
NIF_FUNCTION(max,            2, 1)
NIF_FUNCTION(max_mag,        2, 1)
NIF_FUNCTION(min,            2, 1)
NIF_FUNCTION(min_mag,        2, 1)
NIF_FUNCTION(minus,          1, 1)
NIF_FUNCTION(mul,            2, 1)
NIF_FUNCTION(next_minus,     1, 1)
NIF_FUNCTION(next_plus,      1, 1)
NIF_FUNCTION(next_toward,    2, 1)
// NIF_FUNCTION(or,             2, 1)
NIF_FUNCTION(plus,           1, 1)
NIF_FUNCTION(pow,            2, 1)
NIF_FUNCTION(powmod,         3, 1)
NIF_FUNCTION(quantize,       2, 1)
NIF_FUNCTION(reduce,         1, 1)
NIF_FUNCTION(rem,            2, 1)
NIF_FUNCTION(rem_near,       2, 1)
NIF_FUNCTION(rotate,         2, 1)
NIF_FUNCTION(round_to_int,   1, 1)
NIF_FUNCTION(round_to_intx,  1, 1)
NIF_FUNCTION(scaleb,         2, 1)
NIF_FUNCTION(shift,          2, 1)
NIF_FUNCTION(sqrt,           1, 1)
NIF_FUNCTION(sub,            2, 1)
NIF_FUNCTION(trunc,          1, 1)
NIF_FUNCTION(xor,            2, 1)

